FROM gradle:7.2.0-jdk17

WORKDIR /workspace/app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

EXPOSE 8080

RUN ./gradlew --stop
CMD ["./gradlew", "bootRun"]
